### ISSUE TITLE
Roadmap for this project? 

### ISSUE THREAD

**Issue by shstkvch** [LibrariesHacked/catalogues-api#4]
Hi there

I stumbled across this project while building a scraper to grab books from my local library's Arena web interface. 

My intention is to build a better web UI for UK libraries. I'm wondering what your future plans are for this project, and if you're looking for any contributions?  It would be great to have a one-stop API for UK library data

**Comment by DaveBathnes** [comment]
Hi David

Thanks for the query! I coincidentally started the process of renewing this quite recently. It was originally done a few years ago as a prototype but needs updating (rough code and out of date data)

A one-stop API is definitely the intention. The first step was to be able to search catalogues, but then possible features like automatically renewing items.

And very happy to have contributions and suggestions! It may be a possible start to get an issue list together? Happy for any issues to be raised and I'll start adding a few.

For example, I have up to date data on the systems used by all library services which is part of another project so one step would be to integrate that data source.

Dave

**Comment by shstkvch** [comment]
Hi Dave

That's brilliant, glad to hear you're still working on the project as I think we need tools like this more than ever right now! 

Re data, while doing my own research today I found [this comprehensive Airtable with the UK library catalogues listed](https://airtable.com/shrKkzYDUNMMM6qrJ/tblXNfVTth7GroT5c) (which I reckon you have something to do with!) 

From my point of view, the most compelling features from an API like this would be (in a perfect world):

1. Searching every UK public library at once by keyword and getting useful info for each item returned (title, author, format, ISBNs, availability at locations at the branch level, perhaps with book thumbnails and descriptions pulled in from Google Books or Librarything)
2. Looking up an item by ISBN and see which public libraries in the UK have it available to borrow (perhaps using ISBNthing to bundle together different editions of the same book, perhaps showing how far away the library is)
3. Authenticate with library ID and PIN to view my reservations, renew or reserve books
4. View latest arrivals or curated lists from library staff

Of course you may have different plans for this project entirely, but I'm working on building some of these features in [another repo](https://github.com/abigegg/lanark) and I'd be pleased to contribute here if I can be of help! I'll start adding issues I find and we can see how we go.

David

**Comment by DaveBathnes** [comment]
All great, thanks! And agree with that list.

I've tried running it all up and I think the majority of current problems are basically me being a quarter of the way through a refactor and not finishing it. The refactor was mainly to:

- Remove some clunky error handling
- Remove/archive old connectors. Despite it not being that old, many library services have updated to the latest systems. There are probably only around 7 needed
- Get rid of callbacks and use async/await patterns calls to make it all a bit more readable
- Use the Airtable data (loaded once via API) to replace the data.json.

I can work through the refactoring tasks today and tomorrow and that will get it up and running.

With regards to Axiell - there is also an XML API that it may be worth looking at as a connector. I used it in this renewal script as my local library service uses Axiell.

https://github.com/LibrariesHacked/library-renewals-axiell

Yep, I created that Airtable (though had some help on the data). It's available by this API https://api.librarydata.uk/services/airtable and in this repository

**Comment by shstkvch** [comment]
> With regards to Axiell - there is also an XML API that it may be worth looking at as a connector. I used it in this renewal script as my local library service uses Axiell.

That's amazing, thank you - is this XML API publicly documented anywhere?

I have been wondering what the best approach might be for doing a catalogue search for multiple libraries at once.  

My naive idea for another project (for Glasgow) was to scrape their entire catalogue (using [this search query](https://libcat.csglasgow.org/web/arena/search?p_p_id=searchResult_WAR_arenaportlet&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&_searchResult_WAR_arenaportlet__wu=%2FsearchResult%2F%3Fwicket%3Ainterface%3D%3A0%3AsearchResultPanel%3AcontainerNavigatorTop%3AnavigatorTop%3Alast%3A%3AILinkListener%3A%3A)) and build up a shadow database of all the books, hydrating each entry with metadata from Google Books then query that with Elasticsearch or similar. Doing this for every library in the UK would be an utterly humongous task but it would potentially mean quick search results and more control over how the search is done.

A simpler option would be to only allow searches for particular libraries rather than the entire UK catalogue (which is more practical but feels like a missed opportunity to me) and proxy the search to the appropriate catalogue's search page, then return the results.

You've been looking into this stuff much longer than me, so you might have some better ideas. For this repo, do you have any plans on how you'd like to approach catalogue searching? I see there's a reference to Open Library but sometimes I find their results can be a bit unreliable, and it wouldn't reflect the items actually in the UK catalogues. See [this search](https://openlibrary.org/search?q=Animal+Farm&mode=everything 
) for "Animal Farm" which returns a bunch of inaccessible documents about farming. 

I'll keep an eye on this repo and see if there is anywhere I can contribute, if you open bugs or issues that would give me an idea of what your priorities are :)

**Comment by davidscotson** [comment]
Hey all,

I found this issue and some related repos and comments helpful while looking for a way to talk to Glasgow libraries via web APIs.

I used some info from https://github.com/LibrariesHacked/library-renewals-axiell mentioned above and tweaked it and it seems possible to use that for querying the catalogue as well.

There is an index file which points to various WSDL files describing what the Axiell web service (apparently called Palma) offers here (and at similar urls for other services e.g. wiltshire): 

https://libcat.csglasgow.org/arena.pa.palma/ 
https://libraries.wiltshire.gov.uk/arena.pa.palma/

And some brief testing by pointing Soap-UI at that WSDL to generate some tests and filling in a few values shows it works (see screenshot attached).

<img width="951" alt="Screenshot 2021-06-16 at 19 15 40" src="https://user-images.githubusercontent.com/7288187/122278113-825b1180-cede-11eb-85bc-a5eee703c83d.png">

However, I think the current project code in this repo actually already does everything I wanted anyway since it can talk to both Arena and Iguana systems to query availability so I'll give that a go now, but thought I'd share the above info in case it helped anyone else who is googling for similar things.

**Comment by DaveBathnes** [comment]
Hello!

Just a few notes on roadmap for the project.

This has all been resurrected a little bit. It should now be pretty much up and running with all the connectors working (sometimes they go down!), and has a demo UI at https://www.librarybooks.uk and a Swagger endpoint (currently not complete) at https://www.librarybooks.uk/api

There are some more medium term plans for the project:

1. Take out the actual 'catalogues connector' code and separate into a separate library, published on npm.
2. Leave this project as simply the published API which uses that connector library with the data on individual library services
3. Create additional projects, such as a Chrome/Edge extension which also pull in that catalogues library
4. Make some improvements to the demo UI for this project. However, this will only ever be to really demo the capability of the API rather than a polished front end.
5. Make it more maintainable - I'm going to be looking at regular monitoring scripts against known 'in stock' and 'available' items. If it looks like a particular library service isn't working then I should know about it!
