### ISSUE TITLE
Is there any way to pre-fill the ISBN on the website?

### ISSUE THREAD

**Issue by edent** [LibrariesHacked/catalogues-api#40]
I post book reviews on my blog, and would like to encourage people to borrow those books from the local library. But I don't know where my readers live.

Would it be possible to use a link like `https://www.librarybooks.uk/?isbn=123456789` to pre-fill the ISBN on the website, so users only have to enter their postcode?

**Comment by DaveBathnes** [comment]
Hi, sorry for the delay on this - I did deploy a change for this which should prefill the ISBN field.

It will validate the ISBN before doing so, so that particular example wouldn’t work, but ```9783161484100``` should do. 

The problem with ISBNs is that there can often be multiple ISBNs per title, and normally are. A future update will add an option to do an initial lookup to find all the ISBNs for a title and then do a more comprehensive search with those.

Thanks for the suggestion!
